# Netlify configuration file
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 8080

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  VITE_CONVEX_URL = "Your Convex deployment URL"
  VITE_STRIPE_PUBLISHABLE_KEY = "Your Stripe publishable key"

[functions]
  node_version = "18"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Run post-deployment verification
[[plugins]]
  package = "@netlify/plugin-functions-core"

# Set environment variables for production
[context.production.environment]
  VITE_CONVEX_URL = "https://accomplished-swordfish-668.convex.cloud"