// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnvcoiwgopbkcqnvgdov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFudmNvaXdnb3Bia2NxbnZnZG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDUyNjUsImV4cCI6MjA3MzYyMTI2NX0.w3e_qQulk3UtYwBgHWNbTDd6Dfijjv0_ATtp2SG9m1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});